version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run: echo "installing packages"
      - run: cd ./client && yarn install
      - run: CI=true cd ./client && yarn build
  test:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run: echo "starting test"
      - run: cd ./ && yarn
      - run: cd ./ && yarn test
        
workflows:
    build-and-test:
      jobs:
        - build
        - test